SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_LARGE_POINTS  = 20   # e.g. radius > 2×MIN → large
ASTEROID_MEDIUM_POINTS = 50   # e.g. radius ≤ 2×MIN → medium
ASTEROID_SMALL_POINTS  = 100  # radius ≤ MIN → small
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20

PLAYER_TURN_SPEED = 300

PLAYER_SPEED = 200

# radius of each bullet
SHOT_RADIUS = 5

# speed (pixels/sec) that shots travel
PLAYER_SHOOT_SPEED = 500

PLAYER_SHOOT_COOLDOWN = 0.3
